services:

  deno:
    build: ./deno
    volumes:
      - ./app/templates:/templates
      - ./app/static:/static
    env_file: ./.env
    environment:
      - DENO_DIR=/deno
    container_name: deno
    tty: true

  django:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: django
    volumes:
      - type: bind
        source: ./app
        target: /app
      - ./datasets:/app/datasets

    ports: 
      - "8050:8050"
    restart: "always"
    env_file: ./.env
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
          ignore:
            - "**/__pycache__"
            - "*.pyc"
        - action: rebuild
          path: ./app/requirements.txt
        - action: sync+restart
          path: ./app/core/settings.py
          target: /app/core/settings.py

volumes:
  django_templates:
  django_static:
